[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = [
  "NODE_ENV=development npm install --prefix frontend",
  "npm install --prefix backend"
]

[phases.build]
cmds = ["NODE_ENV=development npm run build --prefix frontend"]

[start]
cmd = "node backend/server.js"
